name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
      - name: Copy settings.xml
        run: cp .github/settings.xml $HOME/.m2/settings.xml
      - name: Build and push Docker image
        run: |
          mvn install -DdockerBuild=true
