name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
      - name: Copy settings.xml
        run: cp settings.xml $HOME/.m2/settings.xml
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and push Docker image
        run: |
          mvn install -DdockerBuild=true
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: retag
        run: |
          docker tag corbel/iam:1.41.0 devialab/iam:1.41.0
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: devialab/iam:1.41.0
